### ISSUE TITLE
User Testing Changes

### ISSUE THREAD

**Issue by Oliversw** [GSG-G7/far-nearer#88]
## Bugs
- [x] Clicking on submit when there are errors in the form causes the button to get stuck in a 'submitting' state, leaving the user unable to submit once they have corrected their input

## General
- [x] Navigation bar can be changed to 'Report a Building' 'View Buildings' 'About'
    - 'Home' and 'Sharing buildings' together in the navigation are a bit confusing. Also we heard feedback that 'Sharing' buildings is a bit confusing so we can go back to 'Reporting'.
-  [x] Font can be changed to 'Nexa' font provided by Hazel
-  [x] Font in Logo should be changed to 'Nexa' font provided by Hazel
-  'Buildings at risk of becoming empty' should also be included in the app. We have changed the copy to reflect this.

## Share Page
- [x] Background cover photo should be changed to new one provided by Hazel
- [x] Subtitle should be 'Report, view, and investigate empty and at risk buildings'
- [x] 'Share Building' button should be changed to 'Report a building'
- [x] 'About the project' section can be removed entirely
- [x] 'Share an empty building' should be changed to 'Report a building'
- [x] Lorem ipsum text underneath should be changed to:
>We wanted to make it easier to report empty and at risk buildings in your community.
>Who Owns Your Neighbourhood is a way to report, view and investigate empty and at risk buildings. Once you have reported a building, this information is made available to community groups who might be interested in buying the property and opening it up for the community.
>We are piloting this project in partnership with community groups in Morecambe and Hastings. **…read more (this should link to about page**)

## View Page
- [x] 'Approved' column of form can be changed to 'Received'
- [x] Placeholder picture for empty houses without a picture should be changed to new one provided by Hazel
- [x] 'Empty Buildings Location' should be changed to 'View Buildings'
- [x] Lorem Ipsum text should be changed to 'These buildings have been reported as empty or at risk by the community. Some may be in the process of verification.'

## About page
- [x] Copy:

Since 2012, the number of empty buildings across England has been steadily rising. Long-term vacant homes now account for £53.6 billion of property in England.

Coastal towns and cities have suffered the biggest rise in long-term empty homes. In many coastal towns, the number of empty homes has doubled in 2018 alone, hitting 939 in Portsmouth, 726 in Hartlepool and 518 in Eastbourne.

There are now more than 216,000 long-term empty homes in England, equivalent to 72 per cent of the government’s annual new homes target. At the same time, there are more than a million families on waiting lists for local authority housing and homelessness it at its highest level for over a decade.

While councils blame poor quality housing and overseas landlords, there is no clear evidence about why the number of empty homes in England is rising. 

Who Owns My Neighbourhood is an independent website built by the Community Interest Company Far Nearer. We wanted to make it easier to report empty and at risk buildings in your community.

So we made Who Owns My Neighbourhood, a way to report, view and investigate empty and at risk buildings.Once you have reported a building, this information is made available to community groups who might be interested in buying the property and opening it up for the community.

### Section 1
- [x] 'Address' should change to 'Location'
- [x] New input underneath 'Location' should be 'Known address (if different to location, optional)'
    - This is because one woman tried to input a building that she knew the address of, but the one in Leaflet maps was different. She found this extremely frustrating so I think just tracking an optional address should help that, since Leaflet mainly uses coordinates. 
- [x] 'Previous use' options should be updated to:
    - Residential
    - Retail
    - Office
    - Community
    - Industrial
    - Other
- [x] 'Owner' should change to 'Who owns the building?'
    - [x] This should have an example underneath that says "E.g. Dan Jones. Has lived overseas since 2014. Last contacted in 2015"
- [x] 'Are they local' should be optional

### Section 2
- [x] 'How long has it been empty' should change to 'Since when has it been empty?'
    - [x] This should have an example underneath that says “Approximately. Feel free to take a guess.”
- [x] 'Since when has it been empty?' input should change from a textbox to a dropdown to select the year that it became empty
- [x] 'Other information' should have an example underneath that says "Broken window on first floor, corner street unit, compulsory purchased at some point, previously tried to contact owner."
- [x] 'What would you like it to be used for?' should have an example underneath that says "E.g. health centre, meeting space, cafe."
- [x] 'Upload building picture' should change to 'Upload a picture of the building'
### Section 3
- [x] 'I agree to sharing this data' should change to 'I consent to share my name and email with Far Nearer and their local community partners: Heart of Hastings and The Exchange CIC'
- [x] 'I would like to receive updates' should change to '- I would like to receive updates from Who Owns Your Neighbourhood'

## To discuss together on a call soon
- Other changes to section 1 of form (Owner). Would it be possible to have the owner and the local section greyed out/unavailable, and only be usable when the user clicks a checkbox to say "I know who owns the building"?
- Possibility to show more information about the buildings in the view buildings page. E.g. date submitted, other information. Would be good to discuss!
- Also possibility in future to click through to a page about the property. Would be good to discuss but I don't think will fit in this sprint!
- One user wanted to click on the list to open the pin on the map. I don't think this is possible right now, but maybe good to talk about for the future.

**Comment by ahmedisam99** [comment]
Hello @Oliversw, could you please clarify some of the stuff written above.

- _General >> `'Buildings at risk of becoming empty' should also be included in the app. We have changed the copy to reflect this.`_
**Where exactly to include? _i.e._ what exactly do you mean by _include_ here?**
- _Share Page >> ` Subtitle should be 'Report, view, and investigate empty and at risk buildings'`_
 **Subtitle? are you referring to the map pop-ups? or something else?**
- _View Page >> `'Approved' column of form can be changed to 'Received'`_
**Technically received is fulfilled once a user submits a new building and it's added to the airtable table. So do you want the same treatment for _received_ as approved but just with different names? or do you want a whole new treatment for this column? _(because you know if it's a different thing then things in the backend and airtable need to change)_**

**To discuss in a call _(probably Monday)_**  
- Form >> Section 1 >> `New input underneath 'Location' should be 'Known address (if different to location, optional)'`

**Comment by Oliversw** [comment]
> General >> 'Buildings at risk of becoming empty' should also be included in the app. We have changed the copy to reflect this.

This was not clear enough from me, sorry! This was some feedback that we received, with the idea that the copy for the app should include some mention of buildings that might be at risk of being empty. Hazel and I sat down and re-wrote some of the copy during the meeting, and that was included in the changes that we asked for. The team doesn't need to do anything about this but I wanted to mention it.

> Share Page >> Subtitle should be 'Report, view, and investigate empty and at risk buildings'
Subtitle? are you referring to the map pop-ups? or something else?

I was trying to refer to this: 
![Screen Shot 2019-11-17 at 1 09 42 AM](https://user-images.githubusercontent.com/9094166/69001483-0ef2b780-08d7-11ea-8ce6-f84be94f72a8.png)

> View Page >> 'Approved' column of form can be changed to 'Received'
Technically received is fulfilled once a user submits a new building and it's added to the airtable table. So do you want the same treatment for received as approved but just with different names? or do you want a whole new treatment for this column? (because you know if it's a different thing then things in the backend and airtable need to change)

I meant more that the display of it on the front end part of the website should read 'Received' but everything else can remain the same. It's more about what the users read.

> Form >> Section 1 >> New input underneath 'Location' should be 'Known address (if different to location, optional)'

I think this would best be done in a call like you suggest because I find it a bit hard to explain otherwise!

---

I'm a bit tired so this might not all make sense but I hope this helps!!
